[build]
  publish = "publish"
  functions = "functions/"

[template.environment]
  COURIER_AUTH_TOKEN = "Add your auth token from Courier. (required)"
  COURIER_EVENT = "Add the notification id or mapped event for the notification Courier wil use."
  COURIER_LIST = "Add the id of the list Courier will send submissions to. (list or recipient required)"
  COURIER_RECIPIENT = "Add the id of the recipient Courier will send submissions to. (recipient or list required)"